name: PR Title Lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@master
        with:
          title-regex: '.+ \(FCS-\d+\)$|chore: merge develop to master|.+ to (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
          error-message: "PR title must end with '(FCS-<number>)' or be 'chore: merge develop to master'"
